// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1293481Evidence.Models;

#nullable disable

namespace _1293481Evidence.Migrations
{
    [DbContext(typeof(StoredProcedureDbpharmaContext))]
    partial class StoredProcedureDbpharmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1293481Evidence.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsNewClient")
                        .HasColumnType("bit");

                    b.Property<string>("ReferrerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoice__D796AAB5E93BEE1D");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("_1293481Evidence.Models.SaleItem", b =>
                {
                    b.Property<int>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SaleItemId")
                        .HasName("PK__SaleItem__C6059401575C490A");

                    b.HasIndex("InvoiceId");

                    b.ToTable("SaleItem", (string)null);
                });

            modelBuilder.Entity("_1293481Evidence.Models.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionTypeId"));

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TransactionTypeId")
                        .HasName("PK__Transact__20266D0BDAFDD8AC");

                    b.ToTable("TransactionType", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionTypeId = 1,
                            TransactionTypeName = "WholeSale"
                        },
                        new
                        {
                            TransactionTypeId = 2,
                            TransactionTypeName = "Retail"
                        },
                        new
                        {
                            TransactionTypeId = 3,
                            TransactionTypeName = "Internal Sale"
                        });
                });

            modelBuilder.Entity("_1293481Evidence.Models.Invoice", b =>
                {
                    b.HasOne("_1293481Evidence.Models.TransactionType", "TransactionType")
                        .WithMany("Invoices")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Invoice__Transac__4BAC3F29");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("_1293481Evidence.Models.SaleItem", b =>
                {
                    b.HasOne("_1293481Evidence.Models.Invoice", "Invoice")
                        .WithMany("SaleItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SaleItem__Invoic__4E88ABD4");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("_1293481Evidence.Models.Invoice", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("_1293481Evidence.Models.TransactionType", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
